[tool.poetry]
name = "poethepoet_plugin_bad_hook"
version = "0.1.0"
description = "A project with an invalid poetry hook."
authors = ["Nat Noordanus <n@natn.me>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poe]
executor = "simple"

[tool.poe.poetry_hooks]
pre_check = "say 'unterminated"

[tool.poe.tasks]
say = "echo"
