"""
Orchestrator: walks ProjectConfig.ConfigOptions and the PoeTask /
PoeExecutor registries, calls __schema_fragment__ hooks, and assembles
the complete root schema.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from poethepoet.schema.context import SchemaContext


# Properties on the root config that should reference shared definitions
# rather than inlining their translation. The translator naturally emits
# correct shapes for these from the annotations, but they're better as
# references — both for editor jump-to-definition and for not duplicating
# the schemas in the JSON file.
_ROOT_PROPERTY_REFS: dict[str, str] = {
    "env": "env_option",
    "envfile": "envfile_option",
    "executor": "executor_option",
    "tasks": "tasks_map",
    "groups": "groups_map",
    "include_script": "include_script",
}


# Properties on every task variant's options that should also $ref a
# shared definition (the same swap applied at the task level).
# Note: task-level executor uses executor_task_option (allows partial
# objects without `type` for project-context inheritance) rather than
# the strict executor_option used at root level (requires `type`).
_TASK_PROPERTY_REFS: dict[str, str] = {
    "env": "env_option",
    "envfile": "envfile_option",
    "executor": "executor_task_option",
    "args": "args_option",
}


# Properties on task_group that should reference shared definitions
# rather than re-translating from TaskGroup TypedDict annotations.
# Without this, group executors emit an undiscriminated `anyOf` and
# nested-in-group tasks bypass task_def validation entirely.
_TASK_GROUP_PROPERTY_REFS: dict[str, str] = {
    "executor": "executor_task_option",
    "tasks": "tasks_map",
}


def build_schema() -> dict:
    """
    Build the complete JSON Schema for the `tool.poe` subtable.

    Returns a self-contained draft-07 schema as a dict. Stable across
    runs (sorted keys at serialization) so committed output diffs cleanly.
    """
    from poethepoet import __version__
    from poethepoet.schema.context import SchemaContext
    from poethepoet.schema.fragments import (
        args_option_schema,
        env_option_schema,
        envfile_option_schema,
        executor_option_schema,
        groups_map_schema,
        include_script_schema,
        task_def_schema,
        task_def_with_case_schema,
        tasks_map_schema,
    )

    ctx = SchemaContext(version=__version__)

    # Build cross-cutting definitions in dependency order. task_def must
    # come before task_def_with_case (which inspects ctx.definitions for
    # the per-task variants). include_script_schema must come after
    # executor_option_schema (depends on executor_task_option).
    env_option_schema(ctx)
    envfile_option_schema(ctx)
    executor_option_schema(ctx)
    args_option_schema(ctx)
    task_def_schema(ctx)
    task_def_with_case_schema(ctx)
    tasks_map_schema(ctx)
    groups_map_schema(ctx)
    include_script_schema(ctx)

    # Apply the $ref swaps inside each task variant: env, envfile,
    # executor, args.
    _apply_task_property_refs(ctx)
    # Same swap on task_group: executor and tasks.
    _apply_task_group_property_refs(ctx)

    # Base root-property schemas come from ProjectConfig.ConfigOptions'
    # __schema_fragment__ hook so subclass overrides (e.g. enums sourced
    # from the task-type registry) are picked up automatically.
    from poethepoet.config.partition import ProjectConfig

    cls = ProjectConfig.ConfigOptions
    fragment = cls.__schema_fragment__(ctx)
    root_properties: dict[str, dict] = dict(fragment["properties"])
    root_required: list[str] = list(fragment.get("required", []))

    # Replace properties listed in _ROOT_PROPERTY_REFS with $refs, preserving
    # the description backfill. $ref-only schemas can't carry sibling
    # keywords under strict draft-07 semantics, but description on $ref is
    # widely supported by editors and meta-validation is permissive.
    for attr_name, type_annotation in cls.get_fields().items():
        schema_key = type_annotation.metadata_get("config_name") or attr_name
        if schema_key in _ROOT_PROPERTY_REFS:
            ref_target = _ROOT_PROPERTY_REFS[schema_key]
            field_schema: dict[str, Any] = {"$ref": f"#/definitions/{ref_target}"}
            if description := cls.description_for_field(attr_name):
                field_schema["description"] = description
            root_properties[schema_key] = field_schema

    # Assemble the root schema.
    schema: dict[str, Any] = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://json.schemastore.org/partial-poe.json",
        "$comment": (f"Generated by poethepoet {ctx.version}. Do not edit by hand."),
        "title": "Poe the Poet configuration",
        "description": (
            "Configuration for Poe the Poet, a task runner that works "
            "well with `pyproject.toml` files."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": sorted(root_required),
        "properties": root_properties,
        "definitions": ctx.definitions,
    }
    return schema


def _apply_task_property_refs(ctx: SchemaContext) -> None:
    """
    Walk each registered task variant in ctx.definitions and swap the
    properties listed in _TASK_PROPERTY_REFS for their corresponding
    `$ref` definitions. This must happen after all cross-cutting
    definitions (env_option, envfile_option, executor_option,
    args_option) are registered.
    """
    from poethepoet.task.base import PoeTask

    task_keys = list(PoeTask.get_task_types())
    for key in task_keys:
        # task_def_schema registers every task type as `{key}_task`, so a
        # missing entry signals a registration bug that would otherwise
        # silently leave that task variant with the inline (laxer) shape.
        # task_def_with_case only covers switch-inner variants, so the
        # absence there is expected.
        assert f"{key}_task" in ctx.definitions, (
            f"Task {key!r} registered with PoeTask but missing the "
            f"`{key}_task` schema definition — did __schema_fragment__ run?"
        )
        for def_name in (f"{key}_task", f"{key}_task_with_case"):
            existing = ctx.definitions
            if def_name not in existing:
                continue
            variant = dict(existing[def_name])
            new_properties = dict(variant["properties"])
            for prop, ref_target in _TASK_PROPERTY_REFS.items():
                if prop in new_properties:
                    new_properties[prop] = {"$ref": f"#/definitions/{ref_target}"}
            variant["properties"] = new_properties
            ctx.mutate_definition(def_name, variant)


def _apply_task_group_property_refs(ctx: SchemaContext) -> None:
    """
    Swap task_group properties for $refs to shared definitions: the
    executor field gets the discriminated executor_task_option union,
    and the tasks field gets tasks_map (patternProperties +
    `$ref: task_def`). Without this, group executors are
    undiscriminated and nested-in-group tasks bypass task_def
    validation.
    """
    existing = ctx.definitions
    if "task_group" not in existing:
        return
    variant = dict(existing["task_group"])
    new_properties = dict(variant["properties"])
    for prop, ref_target in _TASK_GROUP_PROPERTY_REFS.items():
        if prop in new_properties:
            new_properties[prop] = {"$ref": f"#/definitions/{ref_target}"}
    variant["properties"] = new_properties
    ctx.mutate_definition("task_group", variant)
