"""
Orchestrator: walks ProjectConfig.ConfigOptions and the PoeTask /
PoeExecutor registries, calls __schema_fragment__ hooks, and assembles
the complete root schema.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from poethepoet.schema.context import SchemaContext


# Properties on the root config that should reference shared definitions
# rather than inlining their translation. The translator naturally emits
# correct shapes for these from the annotations, but they're better as
# references — both for editor jump-to-definition and for not duplicating
# the schemas in the JSON file.
_ROOT_PROPERTY_REFS: dict[str, str] = {
    "env": "env_option",
    "envfile": "envfile_option",
    "executor": "executor_option",
    "tasks": "tasks_map",
    "groups": "groups_map",
}


# Properties on every task variant's options that should also $ref a
# shared definition (the same swap applied at the task level).
# Note: task-level executor uses executor_task_option (allows partial
# objects without `type` for project-context inheritance) rather than
# the strict executor_option used at root level (requires `type`).
_TASK_PROPERTY_REFS: dict[str, str] = {
    "env": "env_option",
    "envfile": "envfile_option",
    "executor": "executor_task_option",
    "args": "args_option",
}


def build_schema() -> dict:
    """
    Build the complete JSON Schema for the `tool.poe` subtable.

    Returns a self-contained draft-07 schema as a dict. Stable across
    runs (sorted keys at serialization) so committed output diffs cleanly.
    """
    from poethepoet import __version__
    from poethepoet.schema.context import SchemaContext
    from poethepoet.schema.fragments import (
        args_option_schema,
        env_option_schema,
        envfile_option_schema,
        executor_option_schema,
        groups_map_schema,
        task_def_schema,
        task_def_with_case_schema,
        tasks_map_schema,
    )

    ctx = SchemaContext(version=__version__)

    # Build cross-cutting definitions in dependency order. task_def must
    # come before task_def_with_case (which inspects ctx.definitions for
    # the per-task variants).
    env_option_schema(ctx)
    envfile_option_schema(ctx)
    executor_option_schema(ctx)
    args_option_schema(ctx)
    task_def_schema(ctx)
    task_def_with_case_schema(ctx)
    tasks_map_schema(ctx)
    groups_map_schema(ctx)

    # Apply the $ref swaps inside each task variant: env, envfile,
    # executor, args.
    _apply_task_property_refs(ctx)

    # Walk ProjectConfig.ConfigOptions for the root properties.
    from poethepoet.config.partition import ProjectConfig
    from poethepoet.schema.translate import translate_type

    root_properties: dict[str, dict] = {}
    root_required: list[str] = []
    cls = ProjectConfig.ConfigOptions

    for attr_name, type_annotation in cls.get_fields().items():
        schema_key = type_annotation.metadata_get("config_name") or attr_name

        # Use a $ref for cross-cutting properties.
        if schema_key in _ROOT_PROPERTY_REFS:
            ref_target = _ROOT_PROPERTY_REFS[schema_key]
            field_schema: dict[str, Any] = {"$ref": f"#/definitions/{ref_target}"}
        else:
            field_schema = translate_type(type_annotation, ctx)

        if description := cls.description_for_field(attr_name):
            # $ref-only schemas can't carry sibling keywords in strict
            # draft-07, but description on $ref is widely supported by
            # editors. Emit it; meta-validation is permissive.
            field_schema["description"] = description

        root_properties[schema_key] = field_schema

        # Required-ness mirrors PoeOptions.parse logic.
        has_default = hasattr(cls, cls.get_field_attribute(attr_name) or attr_name)
        if not has_default and not type_annotation.is_optional:
            root_required.append(schema_key)

    # Assemble the root schema.
    schema: dict[str, Any] = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://json.schemastore.org/partial-poe.json",
        "$comment": (f"Generated by poethepoet {ctx.version}. Do not edit by hand."),
        "title": "Poe the Poet configuration",
        "description": (
            "Configuration for Poe the Poet, a task runner that works "
            "well with `pyproject.toml` files."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": sorted(root_required),
        "properties": root_properties,
        "definitions": ctx.definitions,
    }
    return schema


def _apply_task_property_refs(ctx: SchemaContext) -> None:
    """
    Walk each registered task variant in ctx.definitions and swap the
    properties listed in _TASK_PROPERTY_REFS for their corresponding
    `$ref` definitions. This must happen after all cross-cutting
    definitions (env_option, envfile_option, executor_option,
    args_option) are registered.
    """
    from poethepoet.task.base import PoeTask

    task_keys = list(PoeTask.get_task_types())
    for key in task_keys:
        for def_name in (f"{key}_task", f"{key}_task_with_case"):
            existing = ctx.definitions
            if def_name not in existing:
                continue
            variant = dict(existing[def_name])
            new_properties = dict(variant["properties"])
            for prop, ref_target in _TASK_PROPERTY_REFS.items():
                if prop in new_properties:
                    new_properties[prop] = {"$ref": f"#/definitions/{ref_target}"}
            variant["properties"] = new_properties
            ctx.mutate_definition(def_name, variant)
