"""
Phase 2 smoke test — verifies the schema package layout is importable.
This file is intentionally not marked `schema` (it's a fast smoke check).
"""


def test_package_imports() -> None:
    from poethepoet.schema import build_schema

    assert callable(build_schema)


def test_package_submodules_importable() -> None:
    # These are the submodules subsequent tasks will populate.
    import poethepoet.schema.context
    import poethepoet.schema.fragments
    import poethepoet.schema.generator
    import poethepoet.schema.translate  # noqa: F401


def test_build_schema_has_required_root_keys() -> None:
    """The generated schema includes the standard top-level keys."""
    from poethepoet.schema import build_schema

    schema = build_schema()
    assert schema["$schema"] == "http://json-schema.org/draft-07/schema#"
    assert schema["$id"] == "https://json.schemastore.org/partial-poe.json"
    assert "$comment" in schema
    assert "Generated by poethepoet" in schema["$comment"]
    assert schema["type"] == "object"
    assert schema["additionalProperties"] is False
    assert "properties" in schema
    assert "definitions" in schema


def test_build_schema_root_properties_include_known_options() -> None:
    """Root-level config keys appear in properties."""
    from poethepoet.schema import build_schema

    schema = build_schema()
    expected = {
        "default_task_type", "default_array_task_type",
        "default_array_item_task_type", "env", "envfile", "executor",
        "include", "include_script", "poetry_command", "poetry_hooks",
        "shell_interpreter", "verbosity", "tasks", "groups",
    }
    assert expected.issubset(schema["properties"].keys())


def test_build_schema_definitions_include_per_task_variants() -> None:
    from poethepoet.schema import build_schema
    from poethepoet.task.base import PoeTask

    schema = build_schema()
    for key in PoeTask.get_task_types():
        assert f"{key}_task" in schema["definitions"]


def test_build_schema_env_property_refs_env_option() -> None:
    from poethepoet.schema import build_schema

    schema = build_schema()
    # The $ref may have a sibling description; check the $ref key only.
    assert schema["properties"]["env"].get("$ref") == "#/definitions/env_option"


def test_build_schema_tasks_property_refs_tasks_map() -> None:
    from poethepoet.schema import build_schema

    schema = build_schema()
    assert schema["properties"]["tasks"].get("$ref") == "#/definitions/tasks_map"


def test_build_schema_executor_property_refs_executor_option() -> None:
    from poethepoet.schema import build_schema

    schema = build_schema()
    assert schema["properties"]["executor"].get("$ref") == (
        "#/definitions/executor_option"
    )
