"""
Smoke tests — verifies the schema package layout is importable.
This file is intentionally not marked `schema` (it's a fast smoke check).
"""

import inspect

from poethepoet.schema import build_schema
from poethepoet.task import parallel, sequence, switch
from poethepoet.task.base import PoeTask


def test_package_imports() -> None:
    from poethepoet.schema import build_schema

    assert callable(build_schema)


def test_package_submodules_importable() -> None:
    # These are the submodules subsequent tasks will populate.
    import poethepoet.schema.context
    import poethepoet.schema.fragments
    import poethepoet.schema.generator
    import poethepoet.schema.translate  # noqa: F401


def test_build_schema_has_required_root_keys() -> None:
    """The generated schema includes the standard top-level keys."""
    schema = build_schema()
    assert schema["$schema"] == "http://json-schema.org/draft-07/schema#"
    assert schema["$id"] == "https://json.schemastore.org/partial-poe.json"
    assert "$comment" in schema
    assert "Generated by poethepoet" in schema["$comment"]
    assert schema["type"] == "object"
    assert schema["additionalProperties"] is False
    assert "properties" in schema
    assert "definitions" in schema


def test_build_schema_root_properties_include_known_options() -> None:
    """Root-level config keys appear in properties."""
    schema = build_schema()
    expected = {
        "default_task_type",
        "default_array_task_type",
        "default_array_item_task_type",
        "env",
        "envfile",
        "executor",
        "include",
        "include_script",
        "poetry_command",
        "poetry_hooks",
        "shell_interpreter",
        "verbosity",
        "tasks",
        "groups",
    }
    assert expected.issubset(schema["properties"].keys())


def test_build_schema_definitions_include_per_task_variants() -> None:
    schema = build_schema()
    for key in PoeTask.get_task_types():
        assert f"{key}_task" in schema["definitions"]


def test_build_schema_cmd_discriminator_has_examples_and_title() -> None:
    """
    CmdTask, the most common task type, carries a SchemaStore-style title
    and examples on its discriminator field.
    """
    schema = build_schema()
    field = schema["definitions"]["cmd_task"]["properties"]["cmd"]
    assert field.get("title") == "Command to execute"
    examples = field.get("examples", [])
    assert isinstance(examples, list)
    assert len(examples) >= 2, examples


def test_build_schema_discriminator_fields_carry_class_docstring() -> None:
    """
    Each task's discriminator property (cmd, expr, ref, script, shell,
    sequence, parallel, switch) carries a description sourced from the
    task class' docstring. Without this, IDE hover on the discriminator
    key shows nothing — the highest-traffic surface for task-authoring.
    """
    schema = build_schema()
    for key in PoeTask.get_task_types():
        task_cls = PoeTask.get_task_class(key)
        expected = inspect.cleandoc(task_cls.__doc__ or "")
        assert expected, f"{task_cls.__name__} has no class docstring"
        field_schema = schema["definitions"][f"{key}_task"]["properties"][key]
        assert field_schema.get("description") == expected, (
            f"{key} discriminator missing description from "
            f"{task_cls.__name__}.__doc__"
        )


def test_build_schema_env_property_refs_env_option() -> None:
    schema = build_schema()
    # The $ref may have a sibling description; check the $ref key only.
    assert schema["properties"]["env"].get("$ref") == "#/definitions/env_option"


def test_build_schema_tasks_property_refs_tasks_map() -> None:
    schema = build_schema()
    assert schema["properties"]["tasks"].get("$ref") == "#/definitions/tasks_map"


def test_build_schema_executor_property_refs_executor_option() -> None:
    schema = build_schema()
    assert schema["properties"]["executor"].get("$ref") == (
        "#/definitions/executor_option"
    )


def test_build_schema_cwd_fields_require_non_whitespace() -> None:
    """
    Every ``cwd`` field carries a ``pattern`` requiring at least one
    non-whitespace character. Empty or whitespace-only cwd values lead
    to opaque execution-time failures; rejecting them at the schema
    level surfaces the problem in the editor.
    """
    schema = build_schema()
    cmd_cwd = schema["definitions"]["cmd_task"]["properties"]["cwd"]
    assert cmd_cwd.get("pattern") == r"\S", cmd_cwd
    include_script_cwd = schema["definitions"]["include_script_item"]["properties"][
        "cwd"
    ]
    assert include_script_cwd.get("pattern") == r"\S", include_script_cwd


def test_build_schema_subtask_options_blocklist() -> None:
    """
    Subtasks declared inside sequence/parallel can't have ``args``, and
    switch case items can't have ``args``/``uses``/``deps`` (runtime:
    sequence.py / parallel.py has_args check, switch.py
    SUBTASK_OPTIONS_BLOCKLIST). The schema wraps each container's
    ``items`` reference in an ``allOf`` that forbids these keys per
    item, using ``{not: {type: object, required: [X]}}`` so bare-string
    refs and inline arrays still pass.
    """
    schema = build_schema()

    def assert_items_forbid(items: dict, blocklist: tuple[str, ...]) -> None:
        assert "allOf" in items, items
        branches = items["allOf"]
        for opt in blocklist:
            assert {
                "not": {"type": "object", "required": [opt]}
            } in branches, f"missing not-required for {opt!r}"

    assert_items_forbid(
        schema["definitions"]["sequence_task"]["properties"]["sequence"]["items"],
        sequence.SUBTASK_OPTIONS_BLOCKLIST,
    )
    assert_items_forbid(
        schema["definitions"]["parallel_task"]["properties"]["parallel"]["items"],
        parallel.SUBTASK_OPTIONS_BLOCKLIST,
    )
    assert_items_forbid(
        schema["definitions"]["switch_task"]["properties"]["switch"]["items"],
        switch.SUBTASK_OPTIONS_BLOCKLIST,
    )


def test_build_schema_use_exec_and_capture_stdout_are_mutex() -> None:
    """
    Tasks that support both ``use_exec`` and ``capture_stdout`` enforce
    mutual exclusion at runtime
    (``cmd.py:58``, ``script.py:51``, ``expr.py:59``). The schema mirrors
    this via an if/then constraint that forbids ``capture_stdout`` when
    ``use_exec`` is true.
    """
    schema = build_schema()
    for key in ("cmd", "script", "expr"):
        variant = schema["definitions"][f"{key}_task"]
        assert variant.get("if") == {
            "properties": {"use_exec": {"const": True}},
            "required": ["use_exec"],
        }, f"{key} missing if-clause"
        assert variant.get("then") == {
            "not": {"required": ["capture_stdout"]}
        }, f"{key} missing then-clause"


def test_build_schema_ref_task_forbids_executor() -> None:
    """
    Ref tasks can't declare an executor — the runtime rejects it in
    ``RefTask.TaskOptions.validate`` (``ref.py:30-37``). The schema removes
    ``executor`` from ``ref_task`` properties so the existing
    ``additionalProperties: false`` catches it at file-author time.
    """
    schema = build_schema()
    ref_task = schema["definitions"]["ref_task"]
    assert "executor" not in ref_task["properties"]
    assert ref_task["additionalProperties"] is False


def test_build_schema_primitive_defaults_propagate() -> None:
    """
    PoeOptions class-level defaults whose value is a JSON primitive
    (bool, int, float, str — including Literal-typed strings) appear
    as ``default:`` annotations on the corresponding schema property.
    Sentinel defaults (``EmptyDict``, ``()``, ``MappingProxyType``) and
    ``None`` defaults are skipped (``None`` typically means "inherit"
    rather than "value is null"). Verified by sampling representative
    fields from across the task / project / arg layers.
    """
    schema = build_schema()

    # Project-level: bare string default sourced from class attribute.
    assert schema["properties"]["default_task_type"].get("default") == "cmd"
    assert schema["properties"]["default_array_item_task_type"].get("default") == "ref"
    assert schema["properties"]["default_array_task_type"].get("default") == "sequence"
    assert schema["properties"]["verbosity"].get("default") == 0
    assert schema["properties"]["poetry_command"].get("default") == "poe"
    assert schema["properties"]["shell_interpreter"].get("default") == "posix"

    # Parallel task: the case that originally motivated this work.
    parallel_props = schema["definitions"]["parallel_task"]["properties"]
    assert parallel_props["prefix"].get("default") == "{name}"
    assert parallel_props["prefix_max"].get("default") == 16
    assert (
        parallel_props["prefix_template"].get("default")
        == "{color_start}{prefix}{color_end} | "
    ), "prefix_template default must include the runtime trailing space"
    assert parallel_props["ignore_fail"].get("default") is False

    # Cmd task: Literal-typed default + bool default.
    cmd_props = schema["definitions"]["cmd_task"]["properties"]
    assert cmd_props["empty_glob"].get("default") == "pass"
    assert cmd_props["use_exec"].get("default") is False

    # Switch task: Literal default.
    switch_props = schema["definitions"]["switch_task"]["properties"]
    assert switch_props["default"].get("default") == "fail"

    # Args item: bool + Literal-string defaults.
    args_props = schema["definitions"]["args_item"]["properties"]
    assert args_props["required"].get("default") is False
    assert args_props["type"].get("default") == "string"

    # Annotated-renamed field: class attr is ``assert_`` with default
    # ``False``; the schema property is ``assert`` per ``config_name``.
    assert (
        schema["definitions"]["expr_task"]["properties"]["assert"].get("default")
        is False
    )


def test_build_schema_no_default_for_sentinels_or_none() -> None:
    """
    Fields whose class-level default is a non-primitive sentinel
    (``EmptyDict``, ``()``, ``MappingProxyType``) or ``None`` must NOT
    carry a ``default:`` annotation. Emitting ``default: {}`` /
    ``default: []`` / ``default: null`` adds noise without value, and
    ``None`` would be actively misleading (it usually means "inherit"
    at runtime, not "literal null").
    """
    schema = build_schema()

    # env / envfile / executor / include — sentinel-defaulted maps/seqs.
    for key in ("env", "envfile", "include", "include_script"):
        assert "default" not in schema["properties"][key], key

    # cwd / capture_stdout — declared as ``X | None = None``.
    cmd_props = schema["definitions"]["cmd_task"]["properties"]
    assert "default" not in cmd_props["cwd"], cmd_props["cwd"]
    assert "default" not in cmd_props["capture_stdout"], cmd_props["capture_stdout"]


def test_build_schema_shell_interpreter_array_min_items() -> None:
    """
    The array branch of ``shell_task.interpreter`` must carry
    ``minItems: 1`` — the runtime annotation is
    ``Annotated[Sequence[ShellInterpreter], Metadata(min_items=1)]``
    (``shell.py:33-37``). Empty interpreter lists would surface as
    opaque execution-time failures, so the constraint belongs at the
    schema layer too.
    """
    schema = build_schema()
    interpreter = schema["definitions"]["shell_task"]["properties"]["interpreter"]
    assert "anyOf" in interpreter, interpreter
    array_branches = [
        branch for branch in interpreter["anyOf"] if branch.get("type") == "array"
    ]
    assert (
        len(array_branches) == 1
    ), f"expected one array branch for interpreter, got {array_branches!r}"
    assert array_branches[0].get("minItems") == 1, array_branches[0]


def test_build_schema_sequence_and_parallel_forbid_capture_stdout() -> None:
    """
    Sequence and parallel tasks can't declare ``capture_stdout`` — the
    runtime rejects it in ``SequenceTask.TaskOptions.validate``
    (``sequence.py:58-61``) and ``ParallelTask.TaskOptions.validate``
    (``parallel.py:107-110``). The schema must drop ``capture_stdout``
    from both task properties (and from the ``_with_case`` shadows used
    inside switches) so the existing ``additionalProperties: false``
    surfaces the error at edit time. Mirrors the ref-task / executor
    treatment in ``ref.py:40-49``.
    """
    schema = build_schema()
    for key in ("sequence_task", "parallel_task"):
        variant = schema["definitions"][key]
        assert (
            "capture_stdout" not in variant["properties"]
        ), f"{key} should not list capture_stdout in properties"
        assert (
            variant["additionalProperties"] is False
        ), f"{key} must keep additionalProperties: false"
        shadow = schema["definitions"][f"{key}_with_case"]
        assert (
            "capture_stdout" not in shadow["properties"]
        ), f"{key}_with_case should not list capture_stdout in properties"


def test_build_schema_switch_control_constrained_to_allowed_task_types() -> None:
    """
    The switch_task ``control`` field is restricted to the task types the
    runtime accepts as a control task (expr/cmd/script per
    ``switch.py:CONTROL_TASK_TYPES``) plus the bare-string form. Other
    task types are excluded.
    """
    schema = build_schema()
    control = schema["definitions"]["switch_task"]["properties"]["control"]
    assert "oneOf" in control
    branches = control["oneOf"]
    refs = {b["$ref"] for b in branches if "$ref" in b}
    types = {b["type"] for b in branches if "type" in b}
    assert "string" in types
    expected = {f"#/definitions/{key}_task" for key in switch.CONTROL_TASK_TYPES}
    assert refs == expected, f"expected {expected}, got {refs}"


def test_build_schema_default_task_type_enum_matches_registry() -> None:
    """
    ``default_task_type`` accepts any string-content task type registered
    via ``MetaPoeTask``. The schema's enum must be sourced from the live
    registry (cmd, expr, ref, script, shell) rather than a hardcoded copy.
    """
    schema = build_schema()
    field_schema = schema["properties"]["default_task_type"]
    expected = list(PoeTask.get_task_types(content_type=str))
    assert field_schema["enum"] == expected
    assert field_schema["type"] == "string"


def test_build_schema_default_array_task_type_enum_excludes_switch() -> None:
    """
    ``default_array_task_type`` accepts list-content task types whose
    bare-array form is well-formed — sequence and parallel. Switch is a
    list-content task but isn't valid here: it requires both ``switch``
    and ``control`` keys, neither of which a bare array can supply.
    """
    schema = build_schema()
    field_schema = schema["properties"]["default_array_task_type"]
    assert field_schema["enum"] == ["parallel", "sequence"]
    assert field_schema["type"] == "string"
    assert "switch" not in field_schema["enum"]


def test_build_schema_default_array_item_task_type_enum_matches_registry() -> None:
    """
    ``default_array_item_task_type`` accepts string-content task types
    (same set as default_task_type). The schema's enum is sourced from
    the registry.
    """
    schema = build_schema()
    field_schema = schema["properties"]["default_array_item_task_type"]
    expected = list(PoeTask.get_task_types(content_type=str))
    assert field_schema["enum"] == expected
    assert field_schema["type"] == "string"
