name: Publish documentation website

on:
  push:
    branches:
      - main
      - doc/init-sphinx

jobs:

  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry

      - name: Install dependencies
        run: poetry install --without dev

      - name: Build sphinx documentation website
        run: poetry run poe docs

      - name: Publish documentation website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          commit_message: ${{ github.event.head_commit.message }}
